#!/usr/bin/env bash
#I hate this assigment. Why are you torturing me??

i=1

while [ $i -le 20 ];
do
echo "$i"
case $i in
4) echo "bad luck from China";;
9) echo "bad luck fron Japan";; 
17) echo "bad luck from Italy";;
esac
i=$((i+1)) 
done 
