#!/usr/bin/env bash
#Seriously. A clock??? Ok. P.S: On second, thought. it's actually cool.
h=0
while [ $h -le 12 ];
do
echo "Hour: $h"
m=1
while [ $m -le 59 ];
do
echo "$m"
m=$(( m+1 ))
done
h=$(( h+1 ))
done
