#!/usr/bin/env bash
#Shakespearean code

K=school
if [ -e "$K" ];
then
echo "school file exists"
if [ -s "$K" ];
then
echo "school file is not empty"
else 
echo "school file is empty"
fi 
if [ -f "$K" ];
then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
